mystudy/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required

from mystudy.views import UserTopicListView, TopicListView, TopicDetailView, TopicCreateView, TopicEditView
from mystudy.views import TopicResourcesCreateView, TopicResourcesListView, TopicResourceEditView, TopicResourceDeleteView
from mystudy.views import UpdatesListView, UpdatesCreateView, UpdateEditView, UpdateDeleteView
from mystudy.views import CategoryCreateView, CategoryDetailView, CategoryListView
from mystudy.views import TopicTagsListView, TopicTagsDetailView
from mystudy.views import update_create_xhr, update_edit_xhr, tr_create_xhr, tr_edit_xhr
from mystudy.models import Topic, Update, TopicResource

from people.decorators import owner_required
#url list
urlpatterns = patterns('',
    url(r'get-json/updates/edit/(?P<nid>\d+)/$', update_edit_xhr, name='update_edit_xhr'),
    url(r'get-json/topic-resource/edit/(?P<nid>\d+)/$', tr_edit_xhr, name='tr_edit_xhr'),
    url(r'category/$', CategoryListView.as_view(), name='topic_category_list'),
    url(r'category/(?P<slug>[-\w]+)/$', CategoryDetailView.as_view(), name='topic_category_detail'),
    url(r'create/$', login_required(TopicCreateView.as_view()), name='topic_create'),
    url(r'tags-cs/(?P<slug>[-\w]+)/$', TopicTagsDetailView.as_view(), name='topic_tags_detail'),
    url(r'tags-cs/$', TopicTagsListView.as_view(), name='topic_tags_list'),
    url(r'user/(?P<person>[-\w]+)/$', UserTopicListView.as_view(), name='user_topic_list'),
    url(r'user/(?P<person>[-\w]+)/(?P<slug>[-\w]+)/edit/$', TopicEditView.as_view(), name='topic_edit'),    
    url(r'user/(?P<person>[-\w]+)/(?P<slug>[-\w]+)/$', TopicDetailView.as_view(), name='topic_detail'),    
    url(r'user/(?P<person>[-\w]+)/(?P<slug>[-\w]+)/resources/$', TopicResourcesListView.as_view(), name='topic_resources'),
    url(r'user/(?P<person>[-\w]+)/(?P<slug>[-\w]+)/updates/$', UpdatesListView.as_view(), name='topic_updates'),
    url(r'user/(?P<person>[-\w]+)/(?P<slug>[-\w]+)/updates/add/$', login_required(update_create_xhr), name='topic_update_create'),
    url(r'user/(?P<person>[-\w]+)/(?P<slug>[-\w]+)/topic-resource/add/$', login_required(tr_create_xhr), name='topic_resource_create'),
    url(r'user/(?P<person>[-\w]+)/(?P<slug>[-\w]+)/updates/edit/(?P<pk>\d+)/$', UpdateEditView.as_view(), name='topic_update_edit'),
    url(r'user/(?P<person>[-\w]+)/(?P<slug>[-\w]+)/topic-resource/edit/(?P<pk>\d+)/$', TopicResourceEditView.as_view(), name='topic_resource_edit'),
    url(r'user/(?P<person>[-\w]+)/(?P<slug>[-\w]+)/updates/delete/(?P<pk>\d+)/$', UpdateDeleteView.as_view(), name='topic_update_delete'),
    url(r'user/(?P<person>[-\w]+)/(?P<slug>[-\w]+)/topic-resource/delete/(?P<pk>\d+)/$', TopicResourceDeleteView.as_view(), name='topic_resource_delete'),    
    url(r'^$', TopicListView.as_view(), name='topic_list'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from mystudy.views import HomeView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^tags/', include('cstags.urls')),
    url(r'^resources/', include('aresource.urls')),
    url(r'^topics/', include('mystudy.urls')),
    url(r'^people/', include('people.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^accounts/', include('myreg.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', HomeView.as_view()),
)

mystudy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from treebeard.mp_tree import MP_Node
from tagging.fields import TagField

from aresource.models import Resource

#from people.models import Person
import tagging
# Create your models here.

class Category(MP_Node):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True, editable=False)
    description = models.TextField(blank=True)

    node_order_by = ['name']

    def __unicode__(self):
        return '%s' % self.name

    def save(self,*args,**kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Category, self).save(*args,**kwargs)

    def get_absolute_url(self):
        return '/topics/category/%s' % self.slug

class Topic(models.Model):
    STATUS_CHOICES = (
        (0, 'Ongoing'),
        (1, 'Completed'),
    )
    person = models.ForeignKey('people.Person')
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True, editable=False)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category)
    tag = TagField()
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    last_viewed = models.DateTimeField(blank=True, null=True)
    deadline = models.DateTimeField(blank=True, null=True)
    dmod_count = models.IntegerField(default=0)
    resources = models.ManyToManyField('aresource.Resource',
        through='mystudy.TopicResource', null=True, blank=True)

    def __unicode__(self):
        return '%s' % self.title

    def save(self,*args,**kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        else:
            ot = Topic.objects.get(id=self.id)
            if ot.deadline != self.deadline:
                self.dmod_count = ot.dmod_count + 1
        super(Topic, self).save(*args,**kwargs)
    
    def get_absolute_url(self):
        return '/topics/user/%s/%s' % (self.person.user.username, self.slug)
        
    class Meta:
        unique_together = (("person", "title"),("person", "slug"))


class Update(models.Model):
    title = models.CharField(max_length=200)
    comment = models.TextField(blank=True)
    topic = models.ForeignKey(Topic)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    eureka = models.BooleanField()
        
    def __unicode__(self):
        return '%s' % self.pk
        
    def get_absolute_url(self):
        return '/topics/users/%s/%s/updates/%d' % (self.topic.person.user, self.topic.slug, self.pk)

class TopicResource(models.Model):
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=140, blank=True)
    note = models.TextField(blank=True)
    resource = models.ForeignKey(Resource)
    video = models.BooleanField()
    rtype = models.ForeignKey('aresource.ResourceType', verbose_name="Resource Type", blank=True, null=True)
    topic = models.ForeignKey('mystudy.Topic')
    eureka = models.BooleanField()

    def __unicode__(self):
        return '%s on %s' % (self.resource, self.topic)

    def get_absolute_url(self):
        return '/topics/%s/%s/%s' % (self.topic.slug, self.resource.id,
            self.id)

mystudy/views.py
import datetime

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.utils import simplejson
from django.core import serializers
from django.template.loader import render_to_string, get_template
from django.template import Context, Template, RequestContext
from django.core.context_processors import csrf


from mystudy.models import Topic, Category, Update, TopicResource
from mystudy.forms import TopicForm, CategoryForm, UpdatesForm, TopicResourceForm

from aresource.models import Resource, ResourceType
from people.models import Person

from people.decorators import owner_required

from tagging.models import Tag, TaggedItem

class TopicListView(ListView):

    context_object_name = 'topic_list'
    queryset = Topic.objects.all()
    template_name = 'mystudy/topic_list.html'


class UserTopicListView(ListView):
    context_object_name = 'topic_list'
    template_name = 'mystudy/user_topic_list.html'
    
    def get_queryset(self):
        self.person = get_object_or_404(Person, user__username__iexact=self.kwargs['person'])
        return Topic.objects.filter(person=self.person).order_by('-last_viewed')
        
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(UserTopicListView, self).get_context_data(**kwargs)
        # Add in the publisher
        context['person'] = self.person
        return context


class TopicDetailView(DetailView):
    context_object_name = 'topic'
    template_name = 'mystudy/topic_detail.html'

    def get_object(self, queryset=None):
        person = self.kwargs.get('person', None)
        slug = self.kwargs.get('slug', None)
        try:
            obj = Topic.objects.get(person__user__username=person, slug=slug)
        except TopicDoesNotExist:
            raise Http404
        if self.request.user == obj.person.user:
            obj.last_viewed = datetime.datetime.now()
            obj.save()
        # Return the object
        return obj
        
    def get_context_data(self, **kwargs):
        context = super(TopicDetailView, self).get_context_data(**kwargs)
        context['update_form'] = UpdatesForm()
        context['tr_form'] = TopicResourceForm()
        context['update_list'] = Update.objects.filter(topic=self.object).order_by('-added')
        context['tr_list'] = TopicResource.objects.select_related().filter(topic=self.object).order_by('-added')
        return context
    
class TopicCreateView(CreateView):
    form_class = TopicForm
    model = Topic
    template_name = 'mystudy/topic_create.html'
        
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.person = get_object_or_404(Person, user=self.request.user)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
        

class TopicEditView(UpdateView):
    context_object_name = 'topic'
    model = Topic
    form_class = TopicForm
    template_name = 'mystudy/topic_edit.html'
    
    def get_object(self, queryset=None):
        person = self.kwargs.get('person', None)
        slug = self.kwargs.get('slug', None)
        try:
            obj = Topic.objects.get(person__user__username=person, slug=slug)
        except TopicDoesNotExist:
            raise Http404
        if not self.request.user == obj.person.user:
            raise Http404
        return obj
    
    
class TopicResourcesCreateView(CreateView):
    form_class = TopicResourceForm
    model = TopicResource
    template_name = 'mystudy/topicresources_create.html'
    success_url = '../..'

    def form_valid(self, form):
        try:
            r = Resource.objects.get(url=form.cleaned_data['resource'])
        except Resource.DoesNotExist:
            r = Resource.objects.create(url=form.cleaned_data['resource'], rtype=form.cleaned_data['rtype'])
            r.save()
        self.object = form.save(commit=False)
        self.object.resource = r
        topic = Topic.objects.get(slug__iexact=self.kwargs['slug'])
        self.object.topic = topic
        self.object.save()
        return super(TopicResourcesCreateView, self).form_valid(form) 
            
    
def tr_create_xhr(request, person, slug):
    if request.method == "POST":
        form = TopicResourceForm(request.POST)
        if form.is_valid():
            try:
                r = Resource.objects.get(url=form.cleaned_data['resource'])
            except Resource.DoesNotExist:
                r = Resource.objects.create(url=form.cleaned_data['resource'], rtype=form.cleaned_data['rtype'])
                r.save()
        obj = form.save(commit=False)
        obj.resource = r
        try:
            topic = Topic.objects.get(person__user=request.user, slug__iexact=slug)
        except Topic.DoesNotExist:
            return Http404
        obj.topic = topic        
        obj.save()
        html = render_to_string('includes/tr_inc.html',{"r":obj,"topic":topic})
        res = {'html':html}
        if request.is_ajax():
            return HttpResponse(simplejson.dumps(res), mimetype="application/json")
        else:
            return HttpResponseRedirect("../..")
    return Http404
    
    
def tr_edit_xhr(request, nid):
    if request.is_ajax():
        if request.method == "GET":
            tr = TopicResource.objects.get(id=nid)
            t = tr.resource.url
            data = {"resource":t}
            form = TopicResourceForm(instance=tr)
#            form.resource=str(tr.resource.url)
#            form.save(commit=False)
            c = {"form":form}
            c.update(csrf(request))
            formt = 'includes/gen_form_inc.html'
            html = render_to_string(formt, c)
            res = {"html":html}
            response = simplejson.dumps(res)
            return HttpResponse(response, mimetype='application/json')
        if request.method == "POST":
            tr = TopicResource.objects.get(id=nid)
            form = TopicResourceForm(request.POST, instance=tr)
            if form.is_valid():
                form = form.save()
                template = 'includes/tr_inc.html'
                html = render_to_string(template, {"r":form})
                res = {"html":html}
                response = simplejson.dumps(res)
                return HttpResponse(response, mimetype='application/json')
            else:
                return Http404
    return Http404
                
        
def update_create_xhr(request, person, slug):
    if request.method == "POST":
        form = UpdatesForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
        else:
            return Http404
        try:
            t = Topic.objects.get(person__user=request.user, slug__iexact=slug)
        except Topic.DoesNotExist:
            return Http404
        form.topic = t
        form.save()
        if request.is_ajax():
            html = render_to_string('includes/update_inc.html',{"u":form,"topic":t})
            res = {"html":html}
            response = simplejson.dumps(res)
            return HttpResponse(response, mimetype='application/json')
        else:
            return HttpResponseRedirect('../..')
    return Http404
    
    
def update_edit_xhr(request, nid):
    if request.is_ajax():
        if request.method == "GET":
            note = Update.objects.get(id=nid)
            form = UpdatesForm(instance=note)
            c = {"form":form}
            c.update(csrf(request))
            formt = 'includes/gen_form_inc.html'
            html = render_to_string(formt, c)
            res = {"html":html}
            response = simplejson.dumps(res)
            return HttpResponse(response, mimetype='application/json')
        if request.method == "POST":
            note = Update.objects.get(id=nid)
            form = UpdatesForm(request.POST, instance=note)
            if form.is_valid():
                form = form.save()
                template = 'includes/update_inc.html'
                html = render_to_string(template, {"u":form})
                res = {"html":html}
                response = simplejson.dumps(res)
                return HttpResponse(response, mimetype='application/json')
            else:
                return Http404
    return Http404
    

class TopicResourcesDetailView(DetailView):
    context_object_name = 'topic_resource'
    template_name = 'mystudy/topicresources_detail.html'
    
#    def get_object(self, queryset=None)


class TopicResourceEditView(UpdateView):
    context_object_name = 'topicresource'
    model = TopicResource
    form_class = TopicResourceForm
    template_name = 'mystudy/topicresources_edit.html'
    success_url = '../../..'
    
    def get_initial(self):
        initial = super(TopicResourceEditView, self).get_initial()
        #TODO: proper auto-generation of code
        self.object = TopicResource.objects.get(id=self.object.id)
        r = self.object.resource.url
        initial.update({'resource': str(r)})
        return initial
        
    def get_object(self, queryset=None):
        person = self.kwargs.get('person', None)
        pk = self.kwargs.get('pk', None)
        try:
            obj = TopicResource.objects.get(id=pk)
        except TopicResource.DoesNotExist:
            raise Http404
        if not self.request.user == obj.topic.person.user:
            raise Http404
        return obj
        
        
    


class TopicResourcesListView(ListView):
    context_object_name = 'tr_list'
    template_name = 'mystudy/topicresources_list.html'
    
    def get_queryset(self):
        self.topic = get_object_or_404(Topic, slug=self.kwargs['slug'])
        return TopicResource.objects.selected_related().filter(topic=self.topic)
        
    def get_context_data(self, **kwargs):

templates/mystudy/category_create.html
{% extends "mystudy_base.html" %}
{% load tagging_tags %}

{% block content %}
	<h2>Add a Study Category</h2>
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" />
	</form>
{% endblock %}

templates/mystudy/category_list.html
{% extends "mystudy_base.html" %}

{% block content %}
<h2>Study Topic Categories</h2>

{% for c in category_list %}

<div class="content-list">
    <ul>
        <li><a href="{{ c.get_absolute_url }}">{{ c.name }} - {{ c.topic_set.count }} Topic{{ c.topic_set.count|pluralize }}</a></li>
    </ul>
</div>
{% endfor %}

{% endblock %}


{% block footer-scripts %}
{{ block.super }}

{% endblock %}

templates/mystudy/topic_create.html
{% extends "mystudy_base.html" %}
{% load tagging_tags %}

{% block content %}
	<h2>Add a Study Topics</h2>
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" />

        <input type="reset" value="Reset form" />
	</form>
{% endblock %}


{% block footer-scripts %}
{{ block.super }}

{% endblock %}

templates/mystudy/topic_detail.html
{% extends "mystudy_base.html" %}
{% load tagging_tags %}
{% load markup %}

{% block content %}
    <h5>Course For <a href={{ topic.person.get_absolute_url }}>{{ topic.person }}</a></h5>

	<h2>{{ topic.title }}</h2>
    
    
	
    <div id="topic-description">
    
    {{ topic.description|markdown }}

    </div>

{% if request.user == topic.person.user %}

    <p>Status: {{ topic.get_status_display }} | Deadline: {{ topic.deadline|date }} - Changed:{{ topic.dmod_count }}
 <a href={% url topic_edit topic.person.user topic.slug %}>Edit Topic</a></p>

    {% endif %}

<p> Filed Under
 <a href={{ topic.category.get_absolute_url }}>{{ topic.category }}</a> on
 {{ topic.created|date:"d/m/y P" }}
     </p>
    
    {% tags_for_object topic as tags %}




        <ul class="tag-list">
    Tags:
        {% for tag in tags %}
        
            <li><a href={% url topic_tags_detail tag.name %}>{{ tag.name }}</a></li>

        {% endfor %}
        </ul>




    <hr />

    <div class="content-list pull-left half tdp">

            <h3>Notes - {{ update_list.count }}</h3>

            {% if request.user == topic.person.user %}
            
            <input class="hide" type="button" id="update-trigger" value="Add Note" />

            <form class="absolute" id="update-form" action="{% url topic_update_create topic.person.user topic.slug %}" method="POST">{% csrf_token %}
                <div id="update-wrapper">
            
                        {{ update_form.as_p }}


                        <input id="update-submit" type="submit" value="Submit" />

                        <input type="reset" value="Reset" />

                </div>
        
            </form>
    

            {% endif %}

            <br />

            
            <span class="view-input">
                <input type="checkbox" class="hide" value="Updates Only" />
                <a href={% url topic_updates topic.person.user topic.slug %}>Notes Only</a>
            </span>
            <input class="hide expand-trigger" type="button" value="Expand All" />
            <select class="list-sort">
                <option value="def" default>Order By...</option>
                <option value="Newest" >Newest</option>
                <option value="Oldest">Oldest</option>
                <option value="AZ">A to Z</option>
                <option value="ZA">Z to A</option>
            </select>

    

            {% include "includes/update_list_inc.html" %}

    </div>



    <div class="content-list pull-right half tdp">


        <h3>Resources - {{ tr_list.count }}</h3>

            {% if request.user == topic.person.user %}

            <input class="hide" type="button" id="tr-trigger" value="Add Resource" />
  
            <form class="absolute" id="tr-form" action="{% url topic_resource_create topic.person.user topic.slug %}" method="POST">{% csrf_token %}
                <div id="tr-wrapper">

                    {{ tr_form.as_p }}

                    <input id="tr-submit" type="submit" value="Submit" />
                    <input type="reset" value="Reset" />


                </div>
            </form>

            {% endif %}

            <br />
 
            <span class="view-input">
                <input type="checkbox" class="hide" value="Resources Only" />
                <a href={% url topic_resources topic.person.user topic.slug %}>Resources Only</a>
            </span>
            <input class="hide expand-trigger" type="button" value="Expand All" />
            <select class="list-sort">
                <option value="def" default>Order By...</option>
                <option value="Newest" >Newest</option>
                <option value="Oldest">Oldest</option>
                <option value="AZ">A to Z</option>
                <option value="ZA">Z to A</option>
            </select>
    

                {% include "includes/tr_list_inc.html" %}

    </div>




{% endblock %}

{% block footer-scripts %}
{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}js/object-edit.js"></script>
<script type="text/javascript">


$('div.sidebar ul.pr-list li').live('mouseover',function(){
    $(this).find('input.addtotopic').removeClass('hide');
    });


$('div.sidebar ul.pr-list li').live('mouseout',function(){
    $(this).find('input.addtotopic').addClass('hide');
    });

$('input.addtotopic').live('click', function(){
    var url = $(this).parent().parent().find('a.tru');
    url = url.attr('href');
    var form = $('form#tr-form');
    form.find('input#id_resource').val(url);
    form.removeClass('hide');
    $('input#tr-trigger').attr("value", 'Cancel Resource');
});


$('.content * form').addClass('hide absolute');

jQuery('#update-trigger').click(function() {
    if (jQuery('#update-form').hasClass('hide')) {
        jQuery('#update-form').removeClass('hide');
        jQuery('input#update-trigger').attr("value", 'Cancel Note');
    }
    else {
        jQuery('#update-form').addClass('hide');
        jQuery('#update-form')[0].reset();
        jQuery('input#update-trigger').attr("value", 'Add Note');
    }
});

jQuery('#tr-trigger').click(function() {
    if (jQuery('#tr-form').hasClass('hide')) {
        jQuery('#tr-form').removeClass('hide');
        jQuery('input#tr-trigger').attr("value", 'Cancel Resource');
    }
    else {
        jQuery('#tr-form').addClass('hide');
        jQuery('#tr-form')[0].reset();
        jQuery('input#tr-trigger').attr("value", 'Add Resource');
    }
});

function addUpdate(e) {
    e.preventDefault();
    var form = jQuery(e.target);
    jQuery.ajax({
        url: form.attr('action'),
        type: form.attr('method'),
        data: form.serialize(),
        dataType: 'json',
        success: function(data, responseStatus, jqXHR){
            var r = data;
            $("ul.update-list").prepend(r.html);
            $('#update-form')[0].reset();
            $('input#update-trigger').attr("value", 'Add Update');
            $('#update-form').addClass('hide');
        }
    });
};

jQuery("form#update-form").submit(function(e){
    addUpdate(e);
});


function addTR(e) {
    e.preventDefault();
    var form = jQuery(e.target);
    jQuery.ajax({
        url: form.attr('action'),
        type: form.attr('method'),
        data: form.serialize(),
        dataType: 'json',
        success: function(data, responseStatus, jqXHR){
            var r = data;
            $("ul.tr-list").prepend(r.html);
            $('#tr-form')[0].reset();
            $('input#tr-trigger').attr("value", 'Add Update');
            $('#tr-form').addClass('hide');
        }
    });
};

jQuery("form#tr-form").submit(function(e){
    addTR(e);
});
</script>

{% endblock %}

templates/mystudy/topic_tag_detail.html
{% extends "mystudy_base.html" %}
{% load tagging_tags %}

{% block content %}
<h2>{{ tag.name }}</h2>



    {% include "includes/topic_list_inc.html" %}


{% endblock %}

{% block footer-scripts %}
{{ block.super }}

{% endblock %}

templates/mystudy/topic_tag_list.html
{% extends "mystudy_base.html" %}

{% block content %}
<div class="span14">
	<h2>Course Tags</h2>

		<ul class="tag-list">
			{% for t in tag_list %}
				<span class="half-col"><li><a href='{% url topic_tags_detail t.name %}'>{{ t.name }} </a></li> X {{ t.count }}</span>
			{% endfor %}
		</ul>
</div>

{% endblock %}

{% block footer-scripts %}
{{ block.super }}

{% endblock %}

templates/mystudy/topicresource_delete.html
{% extends "mystudy_base.html" %}

{% block content %}

<h2>Delete Your Topic Resource</h2>

<form action="" method="POST">{% csrf_token %}

   {{ form.as_p }}

   <input type="submit" value="Submit" />
</form>

{% endblock %}

{% block footer-scripts %}
{{ block.super }}

{% endblock %}

templates/mystudy/topicresources_create.html
{% extends "mystudy_base.html" %}
{% load tagging_tags %}

{% block content %}
	<h2>Add a Study Topic Resource</h2>
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" />
	</form>
{% endblock %}

{% block footer-scripts %}
{{ block.super }}

{% endblock %}

templates/mystudy/topicresources_list.html
{% extends "mystudy_base.html" %}
{% load markup %}

{% block title-tag %} {{ block.super }} {% endblock %}


{% block content %}

<h2>Resources for <a href={{ topic.get_absolute_url }}>{{ topic }}</a></h2>

    <div class="content-list">
        
        {% include "includes/tr_list_inc.html" %}

    </div>

{% endblock %}

{% block footer-scripts %}
{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}js/ocl.js"></script>

{% endblock %}

templates/mystudy/update_delete.html
{% extends "mystudy_base.html" %}

{% block content %}

<h2>Delete Your Update</h2>

<form action="" method="POST">{% csrf_token %}

   {{ form.as_p }}

   <input type="submit" value="Submit" />
</form>

{% endblock %}

{% block footer-scripts %}
{{ block.super }}

{% endblock %}

templates/mystudy/update_form.html
<form action="" method="POST">{% csrf_token %}

   {{ form.as_p }}

   <input type="submit" value="Submit" />
</form>

templates/mystudy/updates_edit.html
{% extends "mystudy_base.html" %}

{% block content %}

<h2>Edit Your Update</h2>

<form action="" method="POST">{% csrf_token %}

   {{ form.as_p }}

   <input type="submit" value="Submit" />
</form>

{% endblock %}

{% block footer-scripts %}
{{ block.super }}

{% endblock %}

templates/mystudy/updates_list.html
{% extends "mystudy_base.html" %}
{% load markup %}

{% block title-tag %} {{ block.super }} {% endblock %}


{% block content %}

<h2>Updates for <a href={{ topic.get_absolute_url }}>{{ topic }}</a></h2>

    <div class="content-list">
    
    {% include "includes/update_list_inc.html" %}

    </div>

{% endblock %}

{% block footer-scripts %}
{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}js/ocl.js"></script>

{% endblock %}
    

templates/mystudy/user_topic_list.html
{% extends "mystudy_base.html" %}
{% load markup %}

{% block content %}
	<h2>Study Topics for {{ person }}</h2>

    <div class="content-list">
		
        {% include "includes/topic_list_inc.html" %}

    </div>

{% endblock %}

{% block footer-scripts %}
{{ block.super }}

{% endblock %}