people/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required

from people.decorators import owner_required

from people.views import PeopleListView, PeopleDetailView, PeopleEditView, AccountEditView
from aresource.views import PersonalResourceCreateView, PersonalResourceCreateViewOC, PersonalResourceEditView, PersonalResourceDetailView, PersonalResourceListView
from aresource.models import PersonalResource

urlpatterns = patterns('',
    url(r'user-resources/edit/(?P<pk>[-\d]+)/$', PersonalResourceEditView.as_view(), name='personalresource_edit'),
    url(r'user-resources/add/$', login_required(PersonalResourceCreateView.as_view()), name='personalresource_create'),
    url(r'user-resources/add/one-click/$', login_required(PersonalResourceCreateViewOC), name='personalresource_create_oc'),
    url(r'user-resources/(?P<person>[-\w]+)/$', PersonalResourceListView.as_view(), name='personalresource_list'),
    url(r'user-resources/(?P<person>[-\w]+)/(?P<pk>\d+)/$', PersonalResourceDetailView.as_view(), name='personalresource_detail'),
    url(r'edit-profile/$', login_required(PeopleEditView.as_view()), name='people_edit'),
    url(r'edit-account/$', login_required(AccountEditView.as_view()), name='account_edit'),
    url(r'(?P<user>[-\w]+)/$', PeopleDetailView.as_view(), name='people_detail'),
    url(r'^$', PeopleListView.as_view(), name='people_list'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from mystudy.views import HomeView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^tags/', include('cstags.urls')),
    url(r'^resources/', include('aresource.urls')),
    url(r'^topics/', include('mystudy.urls')),
    url(r'^people/', include('people.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^accounts/', include('myreg.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', HomeView.as_view()),
)

aresource/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from treebeard.mp_tree import MP_Node
from tagging.fields import TagField
#from people.models import Person

import tagging

class ResourceType(MP_Node):
    name = models.CharField(max_length=60, unique=True)
    slug = models.SlugField(max_length=60, unique=True, editable=False)
    description = models.TextField(blank=True)
    
    def __unicode__(self):
        return '%s' % self.name

    def save(self,*args,**kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(ResourceType, self).save(*args,**kwargs)

    def get_absolute_url(self):
        return '/resources/type/%s' % self.slug

class Resource(models.Model):
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    url = models.URLField(unique=True)
    video = models.BooleanField()
    rtype = models.ForeignKey(ResourceType, verbose_name="Resource Type", blank=True, null=True)
    
    def __unicode__(self):
        return '%s' % self.url
    
    def get_absolute_url(self):
        return '/resources/%s' % self.id
        
        
class PersonalResource(models.Model):
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=140, blank=True)
    note = models.TextField(blank=True)
    resource = models.ForeignKey('aresource.Resource')
    person = models.ForeignKey('people.Person')
    video = models.BooleanField()
    rtype = models.ForeignKey('aresource.ResourceType',verbose_name="Resource Type", blank=True, null=True)
    tag = TagField()
    
    def __unicode__(self):
        return self.resource
        
    def get_absolute_url(self):
        return '/people/user-resources/%s/%s' % (self.person.user, self.pk)
        
        


tagging.register(PersonalResource)

mystudy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from treebeard.mp_tree import MP_Node
from tagging.fields import TagField

from aresource.models import Resource

#from people.models import Person
import tagging
# Create your models here.

class Category(MP_Node):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True, editable=False)
    description = models.TextField(blank=True)

    node_order_by = ['name']

    def __unicode__(self):
        return '%s' % self.name

    def save(self,*args,**kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Category, self).save(*args,**kwargs)

    def get_absolute_url(self):
        return '/topics/category/%s' % self.slug

class Topic(models.Model):
    STATUS_CHOICES = (
        (0, 'Ongoing'),
        (1, 'Completed'),
    )
    person = models.ForeignKey('people.Person')
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True, editable=False)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category)
    tag = TagField()
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    last_viewed = models.DateTimeField(blank=True, null=True)
    deadline = models.DateTimeField(blank=True, null=True)
    dmod_count = models.IntegerField(default=0)
    resources = models.ManyToManyField('aresource.Resource',
        through='mystudy.TopicResource', null=True, blank=True)

    def __unicode__(self):
        return '%s' % self.title

    def save(self,*args,**kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        else:
            ot = Topic.objects.get(id=self.id)
            if ot.deadline != self.deadline:
                self.dmod_count = ot.dmod_count + 1
        super(Topic, self).save(*args,**kwargs)
    
    def get_absolute_url(self):
        return '/topics/user/%s/%s' % (self.person.user.username, self.slug)
        
    class Meta:
        unique_together = (("person", "title"),("person", "slug"))


class Update(models.Model):
    title = models.CharField(max_length=200)
    comment = models.TextField(blank=True)
    topic = models.ForeignKey(Topic)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    eureka = models.BooleanField()
        
    def __unicode__(self):
        return '%s' % self.pk
        
    def get_absolute_url(self):
        return '/topics/users/%s/%s/updates/%d' % (self.topic.person.user, self.topic.slug, self.pk)

class TopicResource(models.Model):
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=140, blank=True)
    note = models.TextField(blank=True)
    resource = models.ForeignKey(Resource)
    video = models.BooleanField()
    rtype = models.ForeignKey('aresource.ResourceType', verbose_name="Resource Type", blank=True, null=True)
    topic = models.ForeignKey('mystudy.Topic')
    eureka = models.BooleanField()

    def __unicode__(self):
        return '%s on %s' % (self.resource, self.topic)

    def get_absolute_url(self):
        return '/topics/%s/%s/%s' % (self.topic.slug, self.resource.id,
            self.id)

people/models.py
from django.db import models
from django.contrib.auth.models import User

from mystudy.models import Topic 
# Create your models here.

class Person(models.Model):
    user = models.ForeignKey(User, unique=True)
    location = models.CharField(max_length=65, blank=True)
    website = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    #private = models.BooleanField(default=False)
    #thumbnail = models.ImageField(blank=True, null=True)
    primary_topic = models.ForeignKey(Topic, related_name='primary', blank=True, null=True)
    
    def __unicode__(self):
        return '%s' % self.user.username
    
    def get_absolute_url(self):
        return '/people/%s' % self.user.username
        
    def is_private(self):
        if private == False:
            return False
        else:
            return True

people/forms.py
from django.forms import ModelForm, URLField, ModelChoiceField

from django.contrib.auth.models import User

from people.models import Person
from mystudy.models import Topic


class PeopleEditForm(ModelForm):
    def __init__(self, *args, **kwargs):
        #self.request = kwargs.pop('request', None)
        super(PeopleEditForm, self).__init__(*args, **kwargs)
        self.fields['primary_topic'] = ModelChoiceField(queryset=Topic.objects.filter(person__user=kwargs['initial']['user']),
        empty_label="Choose A Topic", required=False)
    class Meta:
        model = Person
        
        
class AccountEditForm(ModelForm):
    class Meta:
        model = User
        fields= ('username','first_name','last_name','email')

people/views.py
from django.views.generic import ListView, DetailView, UpdateView
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User

from people.models import Person
from people.forms import PeopleEditForm, AccountEditForm

from mystudy.models import Topic
from aresource.models import PersonalResource

class PeopleListView(ListView):
    model = Person
    context_object_name = 'person_list'
    template_name = 'people/person_list.html'
    
    
class PeopleDetailView(DetailView):
    model = Person
    context_object_name = 'person'
    template_name = 'people/person_detail.html'
    
    def get(self, request, **kwargs):
        # lookup Guide Id in your database and assign it object
        self.object = Person.objects.get(user__username__iexact=kwargs.get('user'))
        # add object to your context_data, so that you can access via your template
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
        
    def get_context_data(self, **kwargs):
        context = super(PeopleDetailView, self).get_context_data(**kwargs)
        context['topic_list'] = Topic.objects.filter(person=self.object)
        context['pr_list'] = PersonalResource.objects.filter(person=self.object)
        return context
        

class PeopleEditView(UpdateView):
    form_class = PeopleEditForm
    template_name = 'people/people_edit.html'
    #success_url = "/people/%(user.username)s/"
    
    def get_form_kwargs(self, **kwargs):
        kwargs = super(PeopleEditView, self).get_form_kwargs(**kwargs)
        kwargs['initial']['user'] = self.request.user
        return kwargs
    
    def get_object(self, queryset=None):
        obj = Person.objects.get(user=self.request.user)
        return obj
        
    
 
class AccountEditView(UpdateView):
    form_class = AccountEditForm
    template_name = 'people/account_edit.html'
    success_url = "/people/%(username)s/"
    
    def get_object(self, queryset=None):
        obj = User.objects.get(id=self.request.user.id)
        return obj

templates/people/account_edit.html
{% extends "people_base.html" %}
{% load tagging_tags %}

{% block content %}
    <h2>Edit Your Account Info</h2>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

{% block footer-scripts %}
{{ block.super }}

{% endblock %}

templates/people/people_edit.html
{% extends "people_base.html" %}
{% load tagging_tags %}

{% block content %}
    <h2>Edit Your Profile Info</h2>
    <a href="{% url account_edit %}">Edit Your Account Info</a>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

{% block footer-scripts %}
{{ block.super }}

{% endblock %}

templates/people/person_detail.html
{% extends "people_base.html" %}
{% load tagging_tags %}

{% block content %}
    <h2>{{ person.user }}</h2>
    <p>Name: {{ person.user.get_full_name }}</p>
    <p>Email: {{ person.user.email }}</p>
    <p>Member Since: {{ person.user.date_joined }}</p>
    <p>Location: {{ person.location }}</p>
    <p>About {{ person.user }}: {{ person.bio }}</p>
    <p>Website: <a href="{{ person.website }}">{{ person.website }}</a></p>

    {% if request.user == person.user %}

    <div class="bookmarklet">
        <h4>CourseSlate Bookmarklet:</h4>
        <p>(Drag the button below onto your browser's toolbar)</p>

    <a id="csbookmarklet"
           href="javascript:(function(){window.open('http://localhost:8000/people/user-resources/add?url='+encodeURI(window.location.href),'height=200,width=150')}())">
           CS+url</a>



    </div>

    {% endif %}


    <div class="content-list user-page half pull-left ocl">

        <h3>Courses - {{ person.topic_set.count }}</h3><br />

            <span class="view-input">
                <input type="checkbox" id="courses" class="hide" value="courses" />
                <a href={% url user_topic_list person.user.username %}>Courses Only</a>
            </span>
            <input class="hide expand-trigger" type="button" value="Expand All" />
            <select class="list-sort">
                <option value="def" default>Order By...</option>
                <option value="Newest" >Newest</option>
                <option value="Oldest">Oldest</option>
                <option value="AZ">A to Z</option>
                <option value="ZA">Z to A</option>
            </select>

        {% include "includes/topic_list_inc.html" %}

    </div>

    <div class="content-list user-page half pull-right">
    
        <h3>Resources - {{ person.personalresource_set.count }}</h3><br />

            <span class="view-input">
                <input type="checkbox" id="resources" class="hide" value="resources" />
                <a href={% url personalresource_list person.user.username %}>Resources Only</a>
            </span>
            <input class="hide expand-trigger" type="button" value="Expand All" />
            <select class="list-sort">
                <option value="def" default>Order By...</option>
                <option value="Newest" >Newest</option>
                <option value="Oldest">Oldest</option>
                <option value="AZ">A to Z</option>
                <option value="ZA">Z to A</option>
            </select>

         {% include "includes/pr_list_inc.html" %}

    </div>
   
{% endblock %}

{% block footer-scripts %}
{{ block.super }}
<script type="text/javascript">

$(document).ready(function (){
    var urlQ = window.location.search;
    urlQ = urlQ.replace('?', '');
    var split = urlQ.split('=');
    if ( urlQ !== '' ) {
        var view = '"' + split[1] + '"'
        var b = $('input:checkbox[id=' + view + ']').attr('checked',true);
        applyFull(b);
    }
});
</script>

{% endblock %}

templates/people/person_list.html
{% extends "people_base.html" %}

{% block content %}
    <h1>Browse Through Members</h1>

    <div class="content-list">
        
    {% include "includes/people_list_inc.html" %}

    </div>
{% endblock %}


{% block footer-scripts %}
{{ block.super }}
<script type="text/javascript">

$('.content-list a[id]').bind('click', function(e){
    e.preventDefault();
    var user = $(this).parent('li').find('p').find('a').text();
    var view = '/?view=' + $(this).attr('id');
    window.location = site_url + 'people/' + user + view;
});

</script>


{% endblock %}