urls.py
from django.conf.urls.defaults import patterns, include, url
from mystudy.views import HomeView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^tags/', include('cstags.urls')),
    url(r'^resources/', include('aresource.urls')),
    url(r'^topics/', include('mystudy.urls')),
    url(r'^people/', include('people.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^accounts/', include('myreg.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', HomeView.as_view()),
)

mystudy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from treebeard.mp_tree import MP_Node
from tagging.fields import TagField

from aresource.models import Resource

#from people.models import Person
import tagging
# Create your models here.

class Category(MP_Node):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True, editable=False)
    description = models.TextField(blank=True)

    node_order_by = ['name']

    def __unicode__(self):
        return '%s' % self.name

    def save(self,*args,**kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Category, self).save(*args,**kwargs)

    def get_absolute_url(self):
        return '/topics/category/%s' % self.slug

class Topic(models.Model):
    STATUS_CHOICES = (
        (0, 'Ongoing'),
        (1, 'Completed'),
    )
    person = models.ForeignKey('people.Person')
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True, editable=False)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category)
    tag = TagField()
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    last_viewed = models.DateTimeField(blank=True, null=True)
    deadline = models.DateTimeField(blank=True, null=True)
    dmod_count = models.IntegerField(default=0)
    resources = models.ManyToManyField('aresource.Resource',
        through='mystudy.TopicResource', null=True, blank=True)

    def __unicode__(self):
        return '%s' % self.title

    def save(self,*args,**kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        else:
            ot = Topic.objects.get(id=self.id)
            if ot.deadline != self.deadline:
                self.dmod_count = ot.dmod_count + 1
        super(Topic, self).save(*args,**kwargs)
    
    def get_absolute_url(self):
        return '/topics/user/%s/%s' % (self.person.user.username, self.slug)
        
    class Meta:
        unique_together = (("person", "title"),("person", "slug"))


class Update(models.Model):
    title = models.CharField(max_length=200)
    comment = models.TextField(blank=True)
    topic = models.ForeignKey(Topic)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    eureka = models.BooleanField()
        
    def __unicode__(self):
        return '%s' % self.pk
        
    def get_absolute_url(self):
        return '/topics/users/%s/%s/updates/%d' % (self.topic.person.user, self.topic.slug, self.pk)

class TopicResource(models.Model):
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=140, blank=True)
    note = models.TextField(blank=True)
    resource = models.ForeignKey(Resource)
    video = models.BooleanField()
    rtype = models.ForeignKey('aresource.ResourceType', verbose_name="Resource Type", blank=True, null=True)
    topic = models.ForeignKey('mystudy.Topic')
    eureka = models.BooleanField()

    def __unicode__(self):
        return '%s on %s' % (self.resource, self.topic)

    def get_absolute_url(self):
        return '/topics/%s/%s/%s' % (self.topic.slug, self.resource.id,
            self.id)

templates/includes/gen_form_inc.html
<form class="ajax-form" action="" method="POST">{% csrf_token %}

   {{ form.as_p }}

   <input type="submit" value="Submit" />
</form>

templates/includes/people_list_inc.html
<ul>
            {% for t in person_list %}
                <li>
                <p><a href={{ t.get_absolute_url }}>{{ t.user }}</a>- Member Since {{ t.user.date_joined }}</p>
                <a id="courses" href='{% url user_topic_list t.user %}'>{{ t.user }}'s Courses - {{ t.topic_set.count }}</a> | <a id="resources" href='{% url personalresource_list t.user %}'>{{ t.user }}'s Resources - {{ t.personalresource_set.count }}</a>
                </li>
            {% endfor %}
 </ul>

templates/includes/pr_list_inc.html
{% load markup %}
{% load people_tags %}


<ul class="ocl pr-list">

    {% for u in pr_list %}
  
        <li>
        
        <h5><a href="{% url personalresource_detail u.person u.id %}">
{% if 0 == u.title|length %}
{{ u.person }} Resource</a></h5>
{% else %}
{{ u.title }}</a></h5> <br />
{% endif %}
        <a class="tru" href='{{ u.resource.url }}'>{{ u.resource.url|sliceit:65 }}</a>
        <div class="oc">

            {{ u.note|markdown }}

            <p>Added <span class="created">{{ u.added|date:"d/m/y" }}</span>| Video: {{ resource.video|yesno:"Y,N" }}<span class="pinfo"> by {{ u.person }}</span></p>

        

        </div>
        </li>

    {% empty %}

        <p>No resources at this time.</p>
    
    {% endfor %}



</ul>

templates/includes/res_set_list_inc.html
{% load markup %}
{% load people_tags %}


<ul class="ocl pr-list">

    {% for u in pr_list %}
  
        <li>
        
        <h5><a href={% url personalresource_detail u.person u.id %}>
{% if 0 == u.title|length %}
{{ u.person }} Resource</a></h5>
{% else %}
{{ u.title }}</a></h5> <br />
{% endif %}
        <a class="tru" href='{{ u.resource.url }}'>{{ u.resource.url|sliceit:65 }}</a>
        <div class="oc">

            {{ u.note|markdown }}

            <p>Added <span class="created">{{ u.added }}</span><span class="pinfo"> by {{ u.person }}</span></p>

        

        </div>
        </li>

    {% empty %}

        <p>No resources at this time.</p>
    
    {% endfor %}



</ul>

templates/includes/resource_options_inc.html
  
        <select id="res-fetch">
                <option value="select-resource" default>Select Resource Set</option>
            {% for o in resource_opt %}
                <option value="{{ o }}">{{ o }}</option>
            {% empty %}
                No Resources
            {% endfor %}

        </select>

templates/includes/resource_options_list_inc.html
{% load markup %}
{% load people_tags %}


<ul class="ocl pr-list">
    {% for r in resources %}
    
        <li>

            {% if tag %}

                {{ tag }}

                    <h5><a href="{% url personalresource_detail r.person r.id %}">
{% if 0 == r.title|length %}
{{ r.person }} Resource</a></h5>
{% else %}
{{ r.title }}</a></h5>
{% endif %}

            {% else %}
            
            <div class="course_id"><a href={{ r.topic.get_absolute_url }}>Course: {{ r.topic }}</a></div>
            <span class="hide">{{ r.topic.slug }}</span>
            
                    <h5>
{% if 0 == r.title|length %}
 Note</h5>
{% else %}
{{ r.title }}</h5>
{% endif %}

            {% endif %}


            <p>
                <a class="tru" href={{ r.resource.url }}>{{ r.resource.url|sliceit:65 }}</a>
            </p>
            <div class="oc">
            
                {{ r.note|markdown }}

            </div>

<p><span class="created">{{ r.added|date:"d/m/y" }}</span>{% if r.rtype %} | <a href="{% url resource_type_detail r.rtype.slug %}">{{ r.rtype }}</a>{% endif %}
        |Video:{{ resource.video|yesno:"Y,N" }}
<input class="hide addtotopic" type="button" value="Add" /></p>
        </li>

    {% empty %}

        <p>No resources yet</p>

    {% endfor %}
</ul>

templates/includes/resources_list_inc.html
{% load people_tags %}

<div class="content-list resource-list">
<ul>
    {% for r in resource_list %}
    
        <li>
            <a class="tru" href="{{ r.url }}">{{ r.url|sliceit:70 }}</a>
            <p><a href="{% url resource_detail r.id %}">Referenced in {{ r.personalresource_set.count }} profiles and {{ r.topicresource_set.all.count }} topics</a></p>
        </li>

    {% empty %}

        <p>No resources</p>

    {% endfor %}
</ul>

</div>

templates/includes/tag_options_inc.html
  
        <select id="tag-fetch">
                <option value="select-resource" default>Select A Tag</option>
            {% for o in tags %}
                <option value="{{ o }}">{{ o }}</option>
            {% empty %}
                No Tags
            {% endfor %}

        </select>

templates/includes/topic_list_inc.html
{% load markup %}



<ul class="ocl topic-list">
            {% for t in topic_list %}
                
                <li>

                    <h5><a href={{ t.get_absolute_url }}>{{ t.title }}</a></h5>

                    <div class="oc">
                        {{ t.description|markdown }}
<p>Added <span class="created">{{ t.created|date:"d/m/y" }}</span> in <a href={{ t.category.get_absolute_url }}>{{ t.category }}</a>
<span class="pinfo"> by <a href="{{ t.person.get_absolute_url }}">{{ t.person }}</a></span></p>
                </div>
                </li>
            
            {% empty %}

                <p>No topics</p>

            {% endfor %}
</ul>

templates/includes/tr_inc.html
{% load markup %}
{% load people_tags %}



       <li>
        
            <h5>{{ r.title }}</h5>

            {% if r.eureka %}
                <b>!!!<span>Eureka! It's all coming together</span></b>
            {% endif %}

            <p><a class="tru" href={{ r.resource.url }}>{{ r.resource.url|sliceit:70 }}</a></p>
            <div class="oc">
            {{ r.note|markdown }}
            <p>Added {{ r.added|date:"d/m/y" }}{% if r.rtype %} |<a href={% url resource_type_detail r.rtype.slug %}>{{ r.rtype }}</a>{% endif %}
            | Video: {{ resource.video|yesno:"Y,N" }}
             {% if request.user == topic.person.user %}
| <a href="{% url topic_resource_delete r.topic.person.user r.topic.slug r.id %}">Delete</a>
 <a href="{% url topic_resource_edit r.topic.person.user r.topic.slug r.id %}">Edit</a>
             {% endif %}</p>
</div>
        </li>

templates/includes/tr_list_inc.html
{% load markup %}
{% load people_tags %}


<ul class="ocl tr-list">
    {% for r in tr_list %}
    
        <li>
            <div class="course_id"><a href= {{ r.topic.get_absolute_url }}>Course: {{ r.topic }}</a></div>
            <h5>{{ r.title }}</h5>

            {% if r.eureka %}
                
            <b>!!!<span>Eureka! It's all coming together</span></b>

            {% endif %}

            <p>
                <a class="tru" href={{ r.resource.url }}>{{ r.resource.url|sliceit:65 }}</a>
            </p>
            <div class="oc">
            
                {{ r.note|markdown }}

                <p>Added <span class="created">{{ r.added|date:"d/m/y" }}</span>{% if r.rtype %} |<a href={% url resource_type_detail r.rtype.slug %}>{{ r.rtype }}</a>{% endif %}
                    | Video: {{ resource.video|yesno:"Y,N" }}

                {% if request.user == topic.person.user %}

                | <a href="{% url topic_resource_delete r.topic.person.user r.topic.slug r.id %}">Delete</a>
                <a class="ajax-edit" href="{% url topic_resource_edit r.topic.person.user r.topic.slug r.id %}">Edit</a>

                {% endif %}</p>

            </div>

        </li>

    {% empty %}

        <p>No topics yet</p>

    {% endfor %}
</ul>

templates/includes/update_inc.html
{% load markup %}



    
        <li>
             <h5>{{ u.title }}</h5>

            {% if u.eureka %}
                <b>!!!<span>Eureka! Now you are getting it!</span></b>
            {% endif %}

             <div class="oc">

             {{ u.comment|markdown }}
                
                <p>Added {{ u.added|date:"d/m/y f a" }}
             
                    {% if request.user == u.topic.person.user %}
| <a href="{% url topic_update_delete u.topic.person.user.username u.topic.slug u.id %}">Delete</a>
 <a href="{% url topic_update_edit u.topic.person.user.username u.topic.slug u.id %}">Edit</a>
             {% endif %}</p>

             
             </div>
        </li>

templates/includes/update_list_inc.html
{% load markup %}



<ul class="ocl update-list">
    {% for u in update_list %}
    
        <li>
             <h5>{{ u.title }}</h5>

            {% if u.eureka %}
                <b>!!!<span> Eureka! Now you are getting it!</span></b>
            {% endif %}

             <div class="oc">

             {{ u.comment|markdown }}
                
                <p>Added <span class="created">{{ u.added|date:"d/m/y f a" }}</span>
             
                    {% if request.user == topic.person.user %}
| <a href="{% url topic_update_delete topic.person.user topic.slug u.id %}">Delete</a>
 <a class="ajax-edit" href="{% url topic_update_edit topic.person.user topic.slug u.id %}">Edit</a>
             {% endif %}</p>

             
             </div>
        </li>


    {% empty %}

        <p>No updates yet.</p>
    
    {% endfor %}
</ul>